In [67]:
import numpy as np
import pandas as pd

In [17]:
a_temp = np.array([[1, 2, 3, 3, 1],
             [6, 8, 11, 10, 7]])
a=a_temp.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [18]:
mean_a = np.array([a.mean(axis = 0)])
mean_a

array([[2. , 8.4]])

In [31]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [59]:
t1 = a_centered[0:5,0:1].T
t2 = a_centered[0:5,1:2]
a_centered_sp = t1 @ t2
a_centered_sp / (np.size(a_centered)-1)

array([[0.88888889]])

In [62]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

In [74]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
                       'author_name':['Тургенев', 'Чехов', 'Островский']}, columns = ['author_id','author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [81]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                    'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'price':[450, 300, 350, 500, 450, 370, 290]}, columns = ['author_id','book_title','price'])
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [83]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'inner')
authors_price


author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [90]:
top5 = authors_price.sort_values(by = 'price')
top5 = top5.head()
top5

author_id author_name            book_title  price
6          3  Островский  Таланты и поклонники    290
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
5          3  Островский                 Гроза    370
0          1    Тургенев           Отцы и дети    450

In [116]:
authors_stat = pd.DataFrame({'author_name':['Тургенев', 'Чехов', 'Островский'],
                        'min_price':[authors_price.loc[(authors_price['author_name'] == 'Тургенев')].price.min(), authors_price.loc[(authors_price['author_name'] == 'Чехов')].price.min(), authors_price.loc[(authors_price['author_name'] == 'Островский')].price.min()],
                        'max_price':[authors_price.loc[(authors_price['author_name'] == 'Тургенев')].price.max(), authors_price.loc[(authors_price['author_name'] == 'Чехов')].price.max(), authors_price.loc[(authors_price['author_name'] == 'Островский')].price.max()],
                        'mean_price':[authors_price.loc[(authors_price['author_name'] == 'Тургенев')].price.mean(), authors_price.loc[(authors_price['author_name'] == 'Чехов')].price.mean(), authors_price.loc[(authors_price['author_name'] == 'Островский')].price.mean()] 
                            }, columns = ['author_name','min_price','max_price','mean_price',])
authors_stat

author_name  min_price  max_price  mean_price
0    Тургенев        300        450  366.666667
1       Чехов        450        500  475.000000
2  Островский        290        370  330.000000

In [118]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая